export const userActions = {
    FETCH_USERS: "FETCH_USERS",
    FETCH_USERS_SUCCESSED: "FETCH_USERS_SUCCESSED",
    FETCH_USERS_FAILED: "FETCH_USERS_FAILED",
    ADD_USER:"ADD_USER",
    ADD_USER_SUCCESSED: "ADD_USER_SUCCESSED",
    ADD_USER_FAILED: "ADD_USER_FAILED",
    DEL_USER: "DEL_USER",
}