export const roleActions = {
    FETCH_ROLE_DATA: "FETCH_ROLE_DATA",
    FETCH_ROLE_SUCCESSED: "FETCH_ROLE_SUCCESSED",
    CREATE_ROLE:'CREATE_ROLE',
    UPDATE_ROLE:'UPDATE_ROLE',
    DELETE_ROLE:'DELETE_ROLE',
    UPDATE_USER_ROLE:'UPDATE_USER_ROLE'
}